name: AuditlogService

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./src/AuditlogService

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2

    #   - name: fetch
    #     run: git fetch --unshallow

    #   - name: Get latest tag
    #     run: |
    #       echo "tag=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    #   - name: Login to Dockerhub
    #     run: docker login -u ${{ secrets.dockerhub_username }} -p ${{ secrets.dockerhub_password }}

    #   - name: Build and Push the Docker image
    #     run: docker build -t marcoippel/auditlogservice:${{ env.tag }} .

    #   - name: Push the Docker image
    #     run: docker push marcoippel/auditlogservice:${{ env.tag }}

    # outputs:
    #   tag: ${{ env.tag }}

  update-dev-image:
    runs-on: ubuntu-latest
    # if: contains(github.ref, 'heads')
    # needs:
    # - build
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: marcoippel/pitstop-infra
        token: ${{secrets.REPO_TOKEN}}

    - run: ls -A

    - id: foo
      uses: marcoippel/pitstop/.github/actions/update-image-tag@v1.0.0
      with:
        image-selector: 'marcoippel/auditlogservice'
        image-tag: ${{ steps.vars.outputs.tag }}
        working-directory: './auditlogservice'
