name: AuditlogService

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/AuditlogService

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: fetch
        run: git fetch --unshallow

      - name: Get latest tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.dockerhub_username }} -p ${{ secrets.dockerhub_password }}

      - name: Build and Push the Docker image
        run: docker build -t marcoippel/auditlogservice:${{ env.tag }} .

      - name: Push the Docker image
        run: docker push marcoippel/auditlogservice:${{ env.tag }}

    outputs:
      tag: ${{ env.tag }}
      sha: $(git rev-parse --short HEAD)

  update-dev-image:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'heads')
    needs: build
    steps:
    - run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
      shell: bash
      
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: marcoippel/pitstop-infra
        token: ${{secrets.REPO_TOKEN}}

    - run: echo ${{needs.build.outputs.tag}}

    # - name: Update tag
    #   uses: marcoippel/pitstop/.github/actions/update-image-tag@${{needs.build.outputs.tag}}
    #   with:
    #     image-selector: 'marcoippel/auditlogservice'
    #     image-tag: ${{ needs.build.outputs.tag }}
    #     working-directory: './auditlogservice'
    #     emailaddress: 'marco@ippelsoft.nl'

    # - run: kustomize edit set image marcoippel/auditlogservice:${{ needs.build.outputs.tag }}
    #   working-directory: ./auditlogservice
    #   shell: bash

    # - run: /usr/bin/git add .
    #   shell: bash

    # - run: |
    #     /usr/bin/git config user.email "$EMAIL"
    #     /usr/bin/git config user.name "$GITHUB_ACTOR"
    #   env:
    #     EMAIL: marco@ippelsoft.nl
    #   shell: bash

    # - run: /usr/bin/git commit -m "Set dev image tag to short sha"
    #   shell: bash

    # - run: /usr/bin/git push
    #   shell: bash
