name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./src/AuditlogService
#         shell: sh
        
    steps:
    - uses: actions/checkout@v2
    
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
