name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/AuditlogService
                
    steps:
    - uses: actions/checkout@v2
    
    - name: Display the path
      run: pwd
      shell: bash
    
    - name: Display the path
      run: ls -R
      shell: bash
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1

